module Scenes.Menu.Common exposing (Model, nullModel, initModel)

{-| Common module

This module is generated by Messenger, don't modify this.

@docs Model, nullModel, initModel

-}

import Lib.Env.Env exposing (Env, addCommonData)
import Lib.Scene.Base exposing (LayerPacker, SceneInitData(..))
import Scenes.Menu.LayerBase exposing (CommonData, nullCommonData)
import Scenes.Menu.LayerSettings exposing (LayerT)
import Scenes.Menu.MainLayer.Export as MainLayer
import Scenes.Menu.MainLayer.Global as MainLayerG
import Scenes.Menu.SceneInit exposing (initCommonData, nullMenuInit)


{-| Model
-}
type alias Model =
    LayerPacker CommonData LayerT


{-| nullModel
-}
nullModel : Model
nullModel =
    { commonData = nullCommonData
    , layers = []
    }


{-| Initialize the model
-}
initModel : Env -> SceneInitData -> Model
initModel env init =
    let
        layerInitData =
            case init of
                MenuInitData x ->
                    x

                _ ->
                    nullMenuInit
    in
    { commonData = initCommonData env layerInitData
    , layers =
        [ MainLayerG.getLayerT <| MainLayer.initLayer (addCommonData nullCommonData env) layerInitData
        ]
    }
