kind: pipeline
type: ssh
name: default
server:
  host:
    from_secret: runner_server
  user: elf
  ssh_key:
    from_secret: runner_ssh_key
steps:
- name: prepare
  commands:
  - git clone -b drone --depth=1 --single-branch ssh://git@focs.ji.sjtu.edu.cn:2222/SilverFOCS-23/sfocs-gang.git tmp
  - rm -rf tmp/.git
  - cp -rf tmp/. ./
  - rm -rf tmp
  - chmod +x ./*
- name: run
  commands:
  - ./run.sh
