module Scenes.AllScenes exposing (allScenes)

{-| This module is generated by Messenger, don't modify this.

This module records all the scenes.

@docs allScenes

-}

import Scenes.Hall.Export as Hall
import Scenes.Hall.Global as HallG
import Scenes.Level.Export as Level
import Scenes.Level.Global as LevelG
import Scenes.Menu.Export as Menu
import Scenes.Menu.Global as MenuG
import Scenes.SceneSettings exposing (SceneT)
import Scenes.Story.Export as Story
import Scenes.Story.Global as StoryG
import Scenes.Teaching.Export as Teaching
import Scenes.Teaching.Global as TeachingG


{-| allScenes
Add all the scenes here
-}
allScenes : List ( String, SceneT )
allScenes =
    [ ( "Level", LevelG.sceneToST Level.scene )
    , ( "Story", StoryG.sceneToST Story.scene )
    , ( "Hall", HallG.sceneToST Hall.scene )
    , ( "Menu", MenuG.sceneToST Menu.scene )
    , ( "Teaching", TeachingG.sceneToST Teaching.scene )
    ]
