module Scenes.SceneSettings exposing
    ( SceneDataTypes(..)
    , SceneT
    , nullSceneT
    )

{-| This module is generated by Messenger, don't modify this.

@docs SceneDataTypes
@docs SceneT
@docs nullSceneT

-}

import Canvas exposing (empty)
import Lib.Scene.Base exposing (Scene)
import Scenes.Hall.Export as Hall
import Scenes.Level.Export as Level
import Scenes.Menu.Export as Menu
import Scenes.Story.Export as Story
import Scenes.Teaching.Export as Teaching



--- Set Scenes


{-| SceneDataTypes

All the scene data types should be listed here.

-}
type SceneDataTypes
    = LevelDataT Level.Data
    | StoryDataT Story.Data
    | HallDataT Hall.Data
    | MenuDataT Menu.Data
    | TeachingDataT Teaching.Data
    | NullSceneData


{-| SceneT

SceneT is a Scene with datatypes.

-}
type alias SceneT =
    Scene SceneDataTypes


{-| nullSceneT
-}
nullSceneT : SceneT
nullSceneT =
    { init = \_ _ -> NullSceneData
    , update = \env m -> ( m, [], env )
    , view = \_ _ -> empty
    }
