module Scenes.Level.Common exposing (Model, nullModel, initModel)

{-| Common module

This module is generated by Messenger, don't modify this.

@docs Model, nullModel, initModel

-}

import Lib.Env.Env exposing (Env, addCommonData)
import Lib.Scene.Base exposing (LayerPacker, SceneInitData(..))
import Scenes.Level.Avatar.Export as Avatar
import Scenes.Level.Avatar.Global as AvatarG
import Scenes.Level.Card.Export as Card
import Scenes.Level.Card.Global as CardG
import Scenes.Level.Enemy.Export as Enemy
import Scenes.Level.Enemy.Global as EnemyG
import Scenes.Level.Frame.Export as Frame
import Scenes.Level.Frame.Global as FrameG
import Scenes.Level.Grids.Export as Grids
import Scenes.Level.Grids.Global as GridsG
import Scenes.Level.LayerBase exposing (CommonData, nullCommonData)
import Scenes.Level.LayerSettings exposing (LayerT)
import Scenes.Level.SceneInit exposing (initCommonData, nullLevelInit)


{-| Model
-}
type alias Model =
    LayerPacker CommonData LayerT


{-| nullModel
-}
nullModel : Model
nullModel =
    { commonData = nullCommonData
    , layers = []
    }


{-| Initialize the model
-}
initModel : Env -> SceneInitData -> Model
initModel env init =
    let
        layerInitData =
            case init of
                LevelInitData x ->
                    x

                _ ->
                    nullLevelInit
    in
    { commonData = initCommonData env layerInitData
    , layers =
        [ GridsG.getLayerT <| Grids.initLayer (addCommonData nullCommonData env) layerInitData
        , EnemyG.getLayerT <| Enemy.initLayer (addCommonData nullCommonData env) layerInitData
        , AvatarG.getLayerT <| Avatar.initLayer (addCommonData nullCommonData env) layerInitData
        , FrameG.getLayerT <| Frame.initLayer (addCommonData nullCommonData env) layerInitData
        , CardG.getLayerT <| Card.initLayer (addCommonData nullCommonData env) layerInitData
        ]
    }
