module Scenes.Level.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Level.Avatar.Export as Avatar
import Scenes.Level.Card.Export as Card
import Scenes.Level.Enemy.Export as Enemy
import Scenes.Level.Frame.Export as Frame
import Scenes.Level.Grids.Export as Grids
import Scenes.Level.LayerBase exposing (CommonData)


{-| LayerDataType
-}
type LayerDataType
    = GridsData Grids.Data
    | AvatarData Avatar.Data
    | EnemyData Enemy.Data
    | FrameData Frame.Data
    | CardData Card.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
