module Scenes.Menu.MainLayer.Global exposing (getLayerT)

{-| Global module

This module is generated by Messenger, don't modify this.

@docs getLayerT

-}

import Canvas exposing (Renderable)
import Lib.Layer.Base exposing (Layer, LayerMsg, LayerTarget)
import Messenger.GeneralModel exposing (GeneralModel)
import Scenes.Menu.LayerBase exposing (CommonData)
import Scenes.Menu.LayerSettings exposing (LayerDataType(..), LayerT)
import Scenes.Menu.MainLayer.Common exposing (EnvC, nullModel)
import Scenes.Menu.MainLayer.Export exposing (Data)


dataToLDT : Data -> LayerDataType
dataToLDT data =
    MainLayerData data


ldtToData : LayerDataType -> Data
ldtToData ldt =
    case ldt of
        MainLayerData x ->
            x

        _ ->
            nullModel


{-| getLayerT
-}
getLayerT : Layer Data CommonData -> LayerT
getLayerT layer =
    let
        update : EnvC -> LayerDataType -> ( LayerDataType, List ( LayerTarget, LayerMsg ), EnvC )
        update env ldt =
            let
                ( rldt, newmsg, newenv ) =
                    layer.update env (ldtToData ldt)
            in
            ( dataToLDT rldt, newmsg, newenv )

        updaterec : EnvC -> LayerMsg -> LayerDataType -> ( LayerDataType, List ( LayerTarget, LayerMsg ), EnvC )
        updaterec env lm ldt =
            let
                ( rldt, newmsg, newenv ) =
                    layer.updaterec env lm (ldtToData ldt)
            in
            ( dataToLDT rldt, newmsg, newenv )

        view : EnvC -> LayerDataType -> Renderable
        view env ldt =
            layer.view env (ldtToData ldt)
    in
    GeneralModel layer.name (dataToLDT layer.data) update updaterec view
