module Scenes.Story.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Story.LayerBase exposing (CommonData)
import Scenes.Story.MainLayer.Export as MainLayer


{-| LayerDataType
-}
type LayerDataType
    = MainLayerData MainLayer.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
